apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phone-pv-claim
  namespace: yavuz-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi